# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Online Corpus

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://onlinecorpus.com"

permalink: /:year/:month/:day/:title/

# other links
twitter_username: georgi_spasov__
email: admin@onlinecorpus.com
linkedIn_username: georgi-spasov-
dribbble_username:

description_footer:  Online Corpus Industries 2019&copy; All rights reserved<br> 

disqus_shortname: georgispasov

google_analytics_id: UA-72449510-4 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 6
